directory/urls.py
from django.conf.urls import *
import views
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ksa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^4/$', RedirectView.as_view(url='/')),
    url(r'^(?P<pk>[\d-]+)/$', views.ksa_view, name='ksa_view'),
    url(r'^update/4/$', RedirectView.as_view(url='/')),
    url(r'^update/(?P<pk>[\w-]+)/$', login_required(views.KSAUpdate.as_view(), login_url='/login/'), name='KSAUpdate'),
    url(r'^toupdate/$', views.toupdate, name='toupdate'),
)

imagestore/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from views import (AlbumListView, ImageListView, UpdateImage, UpdateAlbum, CreateImage, CreateAlbum, DeleteImage, \
                   DeleteAlbum, ImageView)


urlpatterns = patterns('imagestore.views',
                       url(r'^$', AlbumListView.as_view(), name='index'),


                       url(r'^album/add/$', CreateAlbum.as_view(), name='create-album'),
                       url(r'^album/(?P<album_id>\d+)/$', ImageListView.as_view(), name='album'),
                       url(r'^album/(?P<pk>\d+)/edit/$', UpdateAlbum.as_view(), name='update-album'),
                       url(r'^album/(?P<pk>\d+)/delete/$', DeleteAlbum.as_view(), name='delete-album'),

                       url(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

                       url(r'^user/(?P<username>\w+)/albums/$', AlbumListView.as_view(), name='user'),
                       #url(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

                       url(r'^upload/$', CreateImage.as_view(), name='upload'),

                       url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
                       url(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
                       url(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
                       url(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
                       url(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),
                       )

ksa/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ksa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name="my_login"),
    url(r'^logout/$', 'directory.views.user_logout', name="user_logout"),
    url(r'^$', 'directory.views.index', name='index'),
    url(r'^directory/', include('directory.urls')),
	url(r'^gallery/', include('imagestore.urls', namespace='imagestore')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^' + settings.MEDIA_URL[1:] + '(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )
    try:
        urlpatterns += staticfiles_urlpatterns()
    except ImproperlyConfigured:
        pass

directory/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class KSA(models.Model):
	user = models.OneToOneField(User)
	ksa_name = models.CharField(max_length=200, blank=True)
	president_name = models.CharField(max_length=200, blank=True)
	president_contact = models.CharField(max_length=200, blank=True)
	president_photo = models.ImageField(upload_to='president_photos/', blank=True)
	key_people = models.TextField(blank=True)
	housing_info = models.TextField(blank=True)
	facebook_group = models.URLField(max_length=999, blank=True)
	note = models.TextField(blank=True)
	
	def __unicode__(self):
		return self.ksa_name
"""
class Album(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(User)

class Image(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    image = models.FileField(upload_to="images/")
    albums = models.ManyToManyField(Album, blank=True)
"""

imagestore/models/album.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

from bases.album import BaseAlbum
from django.utils.translation import ugettext_lazy as _
from imagestore.utils import load_class, get_model_string

class Album(BaseAlbum):

    class Meta(BaseAlbum.Meta):
        abstract = False
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')
        app_label = 'imagestore'

imagestore/models/image.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

from bases.image import BaseImage
from django.utils.translation import ugettext_lazy as _
from imagestore.utils import load_class, get_model_string

class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        app_label = 'imagestore'

directory/forms.py
from django import forms
from models import KSA

class KSAForm(forms.ModelForm):
    class Meta:
        model = KSA
        fields = ('ksa_name', 'president_name', 'president_contact', 'president_photo', 'key_people', 'housing_info', 'facebook_group', 'note', )

directory/views.py
from django.shortcuts import render, redirect
from models import KSA
from forms import KSAForm
from django.views.generic import UpdateView
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from random import sample

#copied from Imagestore
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from imagestore.models import Album, Image
from imagestore.models import image_applabel, image_classname
from imagestore.models import album_applabel, album_classname
from django.shortcuts import get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from tagging.models import TaggedItem
from tagging.utils import get_tag
from imagestore.utils import load_class
from django.db.models import Q
from imagestore.views import AlbumListView

# Create your views here.
def index(request):
    ksa_list = KSA.objects.all().order_by('ksa_name')
    prez = KSA.objects.get(pk=4)
    image_list = Image.objects.all().order_by('?')[:5]
    album_list = Album.objects.filter(is_public=True).select_related('head')
    return render(request, 'directory/index.html', {'ksa_list': ksa_list, 'prez': prez, 'album_list': album_list, 'image_list': image_list})

def ksa_view(request, pk):
    ksa_list = KSA.objects.all().order_by('ksa_name')
    ksa_instance = KSA.objects.get(pk=pk)
    user = ksa_instance.user
    albums = Album.objects.filter(user=user)
    return render(request, 'directory/instance.html', {'ksa_list': ksa_list, 'ksa_instance': ksa_instance, 'user': user, 'albums': albums})

class KSAUpdate(UpdateView):
    model = KSA
    form_class = KSAForm
    template_name = 'directory/update.html'
    success_url = '/'
    def get_object(self, queryset=None):
        KSA_requested = KSA.objects.get(pk=self.kwargs['pk'])
        if KSA_requested.user == self.request.user:
            return KSA_requested
        else:
            raise Http404

@login_required(login_url='/login/')
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/login/')

@login_required(login_url='/login/')
def toupdate(request):
    needed_id = request.user.ksa.id
    return HttpResponseRedirect('/directory/update/%s' %needed_id)

directory/templates/directory/index.html
{% extends "base.html" %}

{% load thumbnail %}


{% block main-slideshow %}
    <ul class="bxslider" id="main-slider">
       {% for image in image_list %}
           <li>
               {% thumbnail image.image "800x600"  as im %}
                   <img class="white-frame centered" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
               {% endthumbnail %}
           </li>
       {% endfor %}
    </ul>
{% endblock %}

{% block content %}
<center><h2>Обращение президента</h2></center>

{% if prez.president_photo %}
    <div id='prez' class="avatar white-frame" style="background: url({{ MEDIA_URL }}{{ prez.president_photo }}); background-size: cover; background-position: center;">    </div>
{% endif %}

{% if ksa_instance.president_photo %}
	<center><div class="avatar white-frame" style="background: url({{ MEDIA_URL }}{{ ksa_instance.president_photo }}); background-size: cover;"></div></center>
{% endif %}


{% if prez.note %}
	{{prez.note|linebreaks }}
{% endif %}

{% if prez.key_people %}
	<center><h2>Прочие контакты</h2></center>
<center>{{ prez.key_people|linebreaks }}</center>
{% endif %}

<div class="row">
    <div class="col-sm-6">
        <center><h3><a href="{{ prez.facebook_group }}" target="_blank">Официальная группа в Facebook</a></h3><!--<img src="{{ STATIC_URL }}img/facebook.png" alt="">--></center>
    </div>
    <div class="col-sm-6">
        <center><h3><a href="http://www.kazakhembus.com/page/bolashak-contact-us" target="_blank">Представители "Болашақ" в США</a></h3><!--<img src="{{ STATIC_URL }}img/bolashak.jpg" alt="">--></center>
    </div>
</div>

<center><h3>Группы в Facebook по специальностям</h3></center>
<div class="row">
    <div class="col-sm-4">
        <center><a href="https://www.facebook.com/groups/477132862420847/" target="_blank">Agriculture</a></center>
        <center><a href="https://www.facebook.com/groups/1445124539091293/" target="_blank">Art</a></center>
        <center><a href="https://www.facebook.com/groups/287821224731736/" target="_blank">Biology and Chemistry</a></center>
        <center><a href="https://www.facebook.com/groups/675761132477083/" target="_blank">Business and Economics</a></center>
        <center><a href="https://www.facebook.com/groups/1400720803483804/" target="_blank">Computer Science</a></center>
        <center><a href="https://www.facebook.com/groups/243762765817214/" target="_blank">Construction and Architecture</a></center>
        <center><a href="https://www.facebook.com/groups/682508191831315/" target="_blank">Education</a></center>
    </div>
     <div class="col-sm-4">
        <center><a href="https://www.facebook.com/groups/773923339307355/" target="_blank">Engineering Sciences</a></center>
        <center><a href="https://www.facebook.com/groups/654724194614072/" target="_blank">Environmental Sciences</a></center>
        <center><a href="https://www.facebook.com/groups/1438604853074631/"target="_blank">Families</a></center>
        <center><a href="https://www.facebook.com/groups/765020896875926/" target="_blank">Government and Policy</a></center>
        <center><a href="https://www.facebook.com/groups/1425211054426947/" target="_blank">Health Sciences</a></center>
        <center><a href="https://www.facebook.com/groups/1470181926553711/" target="_blank">Human Resources</a></center>
        <center><a href="https://www.facebook.com/groups/1426904884257753/" target="_blank">Internships</a></center>
     </div>
     <div class="col-sm-4">
        <center><a href="https://www.facebook.com/groups/514198158707654/" target="_blank">Law</a></center>
        <center><a href="https://www.facebook.com/groups/339230846228845/" target="_blank">Mechanical Engineering</a></center>
        <center><a href="https://www.facebook.com/groups/684765368266833/" target="_blank">Petroleum Engineering</a></center>
        <center><a href="https://www.facebook.com/groups/249445488584761/" target="_blank">Philological Sciences</a></center>
        <center><a href="https://www.facebook.com/groups/469175499886526/" target="_blank">Physics and Mathematics</a></center>
        <center><a href="https://www.facebook.com/groups/598761830230651/" target="_blank">Tourism and Sports</a></center>
    </div>
</div>


<!--{% include "imagestore/album_list.html" %}-->
{% if user.is_authenticated %}
		    <a href="/directory/toupdate/">Обновить информацию</a>
		    <a href="/gallery/album/add">Новый альбом</a>
		    <a href="/gallery/upload">Новое изображение</a>
		    <a href="/logout/">Log out</a>
{% endif %}
{% endblock %}


{% block bxslider %}
    <script>
        $(document).ready(function(){
            slider = $('.bxslider').bxSlider({mode: 'fade'});
            slider.startAuto();
        });
   </script>
{% endblock %}

directory/templates/directory/instance.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}

{% block tab-name %} - {{ ksa_instance.ksa_name }}{% endblock %}

{% block content %}
<center><h1>{{ ksa_instance.ksa_name }}</p></h1></center>

{% if ksa_instance.president_photo %}
	<center><div class="avatar white-frame" style="background: url({{ MEDIA_URL }}{{ ksa_instance.president_photo }}); background-size: cover; background-position: center;"></div></center>
{% endif %}

{% if ksa_instance.president_name %}
	<center>{{ ksa_instance.president_name }}</center>
	<center>президент</center>
{% endif %}

{% if ksa_instance.president_contact %}
	<center>{{ ksa_instance.president_contact }}</center>
{% endif %}

{% if ksa_instance.key_people %}
	<center><h2>Другие контактные лица</h2></center>
	<center>{{ ksa_instance.key_people|linebreaks }}</p></center>
{% endif %}

{% if ksa_instance.housing_info %}
	<center><h2>Контакты для поиска жилья</h2></center>
	<center>{{ ksa_instance.housing_info|linebreaks }}</p></center>
{% endif %}

{% if ksa_instance.facebook_group %}
	<center><h2><a href="{{ ksa_instance.facebook_group }}" target="_blank">Группа в Facebook</a></h2></center>
{% endif %}

{% if ksa_instance.note %}
	<center>{{ ksa_instance.note|linebreaks }}</center>
{% endif %}

{% if albums %}
    <center><h2>Альбомы</h2></center>
{% endif %}

    <div class='album-list'>
        {% for album in albums %}
            {% if album.get_head  or album.user == request.user %}
            <div class='album'>
                <div class='album-head'>
                    <a href="{{ album.get_absolute_url }}">
                    {% if album.get_head %}
                        {% thumbnail album.get_head.image "150x150" crop='center' as album_head %}
                            <img class="preview white-frame" {% if album.name %} alt="{{ album.name }}" {% endif %} src="{{ album_head.url }}">
                        {% endthumbnail %}
                    {% else %}
                        [{% trans "Empty album" %}]
                    {% endif %}
                    <br>
                    <span class="album-name">{{ album.name }}</span>
                    {% if not view_user and IMAGESTORE_SHOW_USER %}
                        <br>
                        <span class="album-user">
                            {% trans "user" %}: {{ album.user }}
                        </span>
                    {% endif %}
                    </a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

directory/templates/directory/update.html
<form enctype='multipart/form-data' action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

<a href = {% url 'imagestore:user' user.username %} target='_blank'>Редактировать альбомы и изображения</a>

<a href="/">Отмена</a>

<a href="/logout/">Log out</a>